allprojects {
    group = 'io.github.albertoclarit'
    version = '0.1.0'
}

subprojects {
    apply plugin: 'java-library'

    repositories {
        mavenCentral()
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(25)
        }
        withSourcesJar()
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release = 25
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
        testLogging {
            events 'failed', 'skipped'
            exceptionFormat 'full'
        }
    }
}
