[versions]
spring-boot = "4.1.1"
slf4j = "2.0.16"
jackson = "2.19.2"

[libraries]
spring-boot-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure" }
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor" }
spring-boot-starter-jdbc = { module = "org.springframework.boot:spring-boot-starter-jdbc" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-context = { module = "org.springframework:spring-context" }
spring-beans = { module = "org.springframework:spring-beans" }
spring-jdbc = { module = "org.springframework:spring-jdbc" }
spring-tx = { module = "org.springframework:spring-tx" }

flyway-core = { module = "org.flywaydb:flyway-core" }
flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql" }
hikaricp = { module = "com.zaxxer:HikariCP" }
postgresql = { module = "org.postgresql:postgresql" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
